### ISSUE TITLE
Play Install

### ISSUE THREAD

**Issue by Matthancock03** [Matthancock03/proConnect#1]
I believe everyone is good to go, but if you have not already please make sure you can run the project in your local browser. The result should be the sign-in page that I included.

**Comment by Matthancock03** [comment]
@royad @raffyed180 @eyab  @ManbirRandhawa @daisymed @xbrad831x @viva3639 

I think I am going to use Github's ticketing system to assign specific tasks when we start coding. Just want to make sure everyone will get notifications. Comment back in this issue if you get this please. Thank you. 

Matt

**Comment by ManbirRandhawa** [comment]
I received this email

**Comment by xbrad831x** [comment]
Got this in my email

**Comment by daisymed** [comment]
Got this

**Comment by royad** [comment]
Got this
