### ISSUE TITLE
SP2 Home Page

### ISSUE THREAD

**Issue by Matthancock03** [Matthancock03/proConnect#8]
Implement a rough version of the main page. It can be refined later. Just want to have something to demo when we meet again. Share it with me via layoutit before adding to the project. Deadline: 03/24/15

**Comment by xbrad831x** [comment]
Will the home page for the regular user and the premium user look the same, but the premium user may have extra options on top of the regular user options?

**Comment by Matthancock03** [comment]
I would say so.
